/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_glutenproject_ldps_backend_BatchIterator */

#ifndef _Included_io_glutenproject_ldps_backend_BatchIterator
#define _Included_io_glutenproject_ldps_backend_BatchIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_glutenproject_ldps_backend_BatchIterator
 * Method:    nativeHasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_glutenproject_ldps_backend_BatchIterator_nativeHasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_glutenproject_ldps_backend_BatchIterator
 * Method:    nativeNext
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_glutenproject_ldps_backend_BatchIterator_nativeNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_glutenproject_ldps_backend_BatchIterator
 * Method:    nativeCHNext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_glutenproject_ldps_backend_BatchIterator_nativeCHNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_glutenproject_ldps_backend_BatchIterator
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_glutenproject_ldps_backend_BatchIterator_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_glutenproject_ldps_backend_BatchIterator
 * Method:    nativeFetchMetrics
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_glutenproject_ldps_backend_BatchIterator_nativeFetchMetrics
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
