/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ldps_examples_CHColumnVector */

#ifndef _Included_com_ldps_examples_CHColumnVector
#define _Included_com_ldps_examples_CHColumnVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeHasNull
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ldps_examples_CHColumnVector_nativeHasNull
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeNumNulls
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ldps_examples_CHColumnVector_nativeNumNulls
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeIsNullAt
 * Signature: (IJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ldps_examples_CHColumnVector_nativeIsNullAt
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeGetBoolean
 * Signature: (IJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ldps_examples_CHColumnVector_nativeGetBoolean
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeGetByte
 * Signature: (IJI)B
 */
JNIEXPORT jbyte JNICALL Java_com_ldps_examples_CHColumnVector_nativeGetByte
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeGetShort
 * Signature: (IJI)S
 */
JNIEXPORT jshort JNICALL Java_com_ldps_examples_CHColumnVector_nativeGetShort
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeGetInt
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_com_ldps_examples_CHColumnVector_nativeGetInt
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeGetLong
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_com_ldps_examples_CHColumnVector_nativeGetLong
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeGetFloat
 * Signature: (IJI)F
 */
JNIEXPORT jfloat JNICALL Java_com_ldps_examples_CHColumnVector_nativeGetFloat
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeGetDouble
 * Signature: (IJI)D
 */
JNIEXPORT jdouble JNICALL Java_com_ldps_examples_CHColumnVector_nativeGetDouble
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_ldps_examples_CHColumnVector
 * Method:    nativeGetString
 * Signature: (IJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ldps_examples_CHColumnVector_nativeGetString
  (JNIEnv *, jobject, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
