/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ldps_examples_CHNativeBlock */

#ifndef _Included_com_ldps_examples_CHNativeBlock
#define _Included_com_ldps_examples_CHNativeBlock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ldps_examples_CHNativeBlock
 * Method:    nativeNumRows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ldps_examples_CHNativeBlock_nativeNumRows
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ldps_examples_CHNativeBlock
 * Method:    nativeNumColumns
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ldps_examples_CHNativeBlock_nativeNumColumns
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ldps_examples_CHNativeBlock
 * Method:    nativeColumnType
 * Signature: (JI)[B
 */
JNIEXPORT jstring JNICALL Java_com_ldps_examples_CHNativeBlock_nativeColumnType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ldps_examples_CHNativeBlock
 * Method:    nativeTotalBytes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ldps_examples_CHNativeBlock_nativeTotalBytes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ldps_examples_CHNativeBlock
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ldps_examples_CHNativeBlock_nativeClose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
