/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ldps_examples_ExpressionEvaluatorJniWrapper */

#ifndef _Included_com_ldps_examples_ExpressionEvaluatorJniWrapper
#define _Included_com_ldps_examples_ExpressionEvaluatorJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ldps_examples_ExpressionEvaluatorJniWrapper
 * Method:    nativeInitNative
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_ldps_examples_ExpressionEvaluatorJniWrapper_nativeInitNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ldps_examples_ExpressionEvaluatorJniWrapper
 * Method:    nativeFinalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ldps_examples_ExpressionEvaluatorJniWrapper_nativeFinalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_ldps_examples_ExpressionEvaluatorJniWrapper
 * Method:    nativeDoValidate
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ldps_examples_ExpressionEvaluatorJniWrapper_nativeDoValidate
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ldps_examples_ExpressionEvaluatorJniWrapper
 * Method:    nativeCreateKernelWithIterator
 * Signature: (J[B[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_ldps_examples_ExpressionEvaluatorJniWrapper_nativeCreateKernelWithIterator
  (JNIEnv *, jobject, jlong, jbyteArray, jobjectArray);

/*
 * Class:     com_ldps_examples_ExpressionEvaluatorJniWrapper
 * Method:    nativeCreateKernelWithRowIterator
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_ldps_examples_ExpressionEvaluatorJniWrapper_nativeCreateKernelWithRowIterator
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ldps_examples_ExpressionEvaluatorJniWrapper
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ldps_examples_ExpressionEvaluatorJniWrapper_nativeClose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
