/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_glutenproject_examples_Query */

#ifndef _Included_io_glutenproject_examples_Query
#define _Included_io_glutenproject_examples_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_glutenproject_examples_Query
 * Method:    sqlQuery
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_glutenproject_examples_Query_sqlQuery
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
